import { Navbar } from "@/app/components/Navbar";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Modal } from "./components/modals/Modal";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
          <Modal actionLabel="Continue" title="Log in or sign up" isOpen/>
          <Navbar />
        {children}
      </body>
    </html>
  );
}
